### ISSUE TITLE
ios not available

### ISSUE THREAD

**Issue by Zocoo** [IoTDevice/flutter_oneshot#1]
ios start method error
ios version 17.5
error msg：
Error===, type '_OneByteString' is not a subtype of type 'Map<dynamic, dynamic>'

**Comment by IoTServ** [comment]
Current version not support iOS, there is no energy to support iOS

**Comment by IoTServ** [comment]
这当时只是为了支持斐讯插排的附属项目，没有花太大的精力支持iOS平台
